MODEL:
  TYPE: swinv2
  NAME: mim_satvision_pretrain-huge
  DROP_PATH_RATE: 0.1
  SWINV2:
    IN_CHANS: 14 
    EMBED_DIM: 352 
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32]
    WINDOW_SIZE: 8 
    NORM_PERIOD: 6
DATA:
  IMG_SIZE: 128
  MASK_PATCH_SIZE: 8
  MASK_RATIO: 0.6
TRAIN:
  USE_CHECKPOINT: True
  EPOCHS: 50
  WARMUP_EPOCHS: 1 
  BASE_LR: 3e-4
  MIN_LR: 2e-4
  WARMUP_LR: 1e-4 
  WEIGHT_DECAY: 0.05
  OPTIMIZER:
    NAME: adamw 
  LR_SCHEDULER:
    NAME: 'multistep'
    GAMMA: 0.1
    MULTISTEPS: [700,]
PRINT_FREQ: 10 
SAVE_FREQ: 1000
VALIDATION_FREQ: 20
TAG: mim_pretrain_675m_2m_128_window8_onecycle_hackathon_adamw
